### ISSUE TITLE
Process does not exit as expected when calling `client.destroy()`

### ISSUE THREAD

**Issue by Iodine-** [splitio/javascript-client#248] opened 2019-04-23 13:55 UTC
When initializing the SDK with `mode: 'consumer'` against REDIS, calling `client.destroy()` no longer immediately(within a reasonable window) terminates the process.  This is especially problematic when using the SDK in lambda functions where the lambda remains running until the SDK vacates the stack.

This appears to be due to a change (https://github.com/splitio/javascript-client/commit/6ce13051b43879d886bf0038e1833ddcbd88d257) where the default `startup.readyTimeout` was increased to 15 seconds.  As the timeout is using `setTimeout()`, as long as the timeout is pending, it remains active on the callstack and holds the process.

**Comment by NicoZelaya** [comment] 2019-04-24 13:15
Hey Matt!! Hope you're doing great lately, it's been a while!

I'm sorry for the inconveniences this caused to you and your team. I'll probably use your PR as the starting point but will fix the other race condition with the Redis issue along with it. 

I understand you're unblocked by setting the readyTimeout to 0, but if that's NOT the case let me know and I'll try to move that piece into a stable release sooner.
At the same time I'll look into having a Lambda function automated test too to ensure we don't have any regressions or similar issues in the future.

Again, I'm truly sorry for the inconveniences and grateful for your patience as well as your contribution!

Have a wonderful day,
Nico.

**Comment by Iodine-** [comment] 2019-04-24 13:40
Hey @NicoZelaya - yes sir it has been some time!

Please feel free to use the PR as you see fit - cleaning up that race condition at the same time sounds great.  I was poking around with it, to the point of logging out the redis connection status immediately before setting the key, and it returned ready still - even when getting the error, which is where I left my investigation.  My gut tells me it's something to do with the queuing redis commands prior to ready + immediately destroying the client, but it's just a guess.

Yes we can mitigate the changes introduced by setting the `readyTimeout:0` - which is what we will do today.  We probably should have done that in the first place to insulate ourselves from this type of side-effect, but we just didn't think about it. 

As for the testing - I was confused at first when I went to add a test for my change, because it looked as if there already was one testing the timeout ([READINESS GATE / Cancel timeout if ready fired](https://github.com/splitio/javascript-client/blob/development/src/readiness/__tests__/readiness.spec.js#L145-L164)), but upon closer inspection it actually is just testing that when the `setTimeout` expires, that the logic inside considers the `status` and does not emit the `Events.SDK_READY_TIMED_OUT` event.  (aka. test name is a bit misleading) 

In addition - the same test does not seem to account for `mode: 'CONSUMER'` - I could be wrong here (I am by no means intimately familiar with the code) but I do not believe in `CONSUMER` mode that there is no `producer`, which I believe is where the `readiness.splits.SDK_SPLITS_ARRIVED` and `readiness.segments.SDK_SEGMENTS_ARRIVED` events are emitted.  The test assumes those are emitted however and manually emits them - which may tailor the test to only catch non-consumer mode setups.  This of course it all just my uninformed observations.  Please add appropriate pinches of salt to taste.

Hope it helps!

**Comment by NicoZelaya** [comment] 2019-05-02 17:49
hey @Iodine- !

I'm sorry it took some time for me to come back to this. Again, sorry for my overlook when I changed the default readyTimeout. 

In the past we used the offline queue provided by ioredis, so any command issued to a not yet ready or disconnected redis instance was just queued silently and maybe never executing. This year we made some changes there to try and detect this, also removing that queue by default and replaced it whit a custom one which we will only use until the connection is ready. And after disconnection (upon calling destroy) we won't queue commands that will never execute.

The hanging timeout thing I think it's quite clear. While it would not be truly reliable to try and compare timestamps from when a test started and ended, I wanted to add coverage, so you'll see that on the tests I'm setting high values for the ready timeout, which would cause or CI tests to timeout too if it's not cleared as it should.

Regarding the other error, it's caused when the SDK tries to perform an operation in Redis after the disconnect() function was invoked. 
In the case of getTreatment/s was either the RPUSH of the impressions or the EXPIRE we set if the SDK is just creating the impressions queue, but we will have something similar with a validation for .track() in future releases.
I'm not too proud of how the code is now but it seems to do the trick. But in any case I'll keep testing it and trying to find the best way to ensure that we disconnect properly but we don't miss executing the Redis operations we trigger.

And finally, in regards to BUR not working for Redis mode, I've started by emitting the readiness events in a dummy way to try and reduce the amount of code changes when moving from one mode to the other. 
I might change that in the future to be tied to the "ready" event of ioredis directly. If you don't mind me asking, what would you prefer here? 

You can see the PR addressing these here: https://github.com/splitio/javascript-client/pull/252

I'll be waiting for your review! Thanks in advance for your help and impeccable feedback as always.
Nico.

**Comment by NicoZelaya** [comment] 2019-05-15 21:06
Hey Matt! 

I'm closing this since Bilal already notified you through our Support channel, but feel free to reach out if there's any other issue with it!

Best regards,
Nico.

**Closed by NicoZelaya** 2019-05-15 21:06 UTC
